import { jsPDF } from "jspdf";

type AIReport = {
  title: string;
  subtitle: string;
  snapshot: string;
  strengths: string[];
  opportunities: string[];
  topPriorities: string[];
  buyNext: string[];
  bestPlacesToShop: {
    challenge: string;
    whatToShop: string;
    whereToBuy: string[];
    reason: string;
  }[];
  plan30Days: {
    days: string;
    focus: string;
    actions: string[];
  }[];
  confidenceAdvice: string;
};

type PDFInput = {
  aiReport: AIReport;
  result: {
    overall_score: number;
    confidence_level: string;
    category_scores: Record<string, number>;
  };
  categoryLabels: Record<string, string>;
  getStyleArchetype: (
    overallScore: number,
    categoryScores: Record<string, number>
  ) => {
    title: string;
    description: string;
  };
};

export function downloadAIReportPDF({
  aiReport,
  result,
  categoryLabels,
  getStyleArchetype,
}: PDFInput) {
  const doc = new jsPDF({
    orientation: "p",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 42;
  const contentWidth = pageWidth - marginX * 2;
  let y = 48;

  const colors = {
    bg: [248, 250, 252] as [number, number, number],
    text: [15, 23, 42] as [number, number, number],
    muted: [100, 116, 139] as [number, number, number],
    line: [226, 232, 240] as [number, number, number],
    orange: [234, 136, 44] as [number, number, number],
    blue: [59, 130, 246] as [number, number, number],
    green: [34, 197, 94] as [number, number, number],
    amber: [245, 158, 11] as [number, number, number],
    purple: [168, 85, 247] as [number, number, number],
    teal: [20, 184, 166] as [number, number, number],
    pink: [236, 72, 153] as [number, number, number],
    card: [255, 255, 255] as [number, number, number],
    darkCover: [10, 18, 40] as [number, number, number],
    darkCover2: [20, 35, 75] as [number, number, number],
  };

  const archetype = getStyleArchetype(
    result.overall_score,
    result.category_scores
  );

  const categoryCards = Object.entries(result.category_scores).map(
    ([key, value]) => ({
      label: categoryLabels[key] || key,
      value,
    })
  );

  function addFooter() {
    const footerY = pageHeight - 24;
    doc.setDrawColor(...colors.line);
    doc.line(marginX, footerY - 16, pageWidth - marginX, footerY - 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...colors.muted);
    doc.text("Generated by StyleScore", marginX, footerY);
    doc.text("stylescore.live", pageWidth - marginX, footerY, {
      align: "right",
    });
    doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth / 2, footerY, {
      align: "center",
    });
  }

  function ensureSpace(requiredHeight: number) {
    if (y + requiredHeight > pageHeight - 56) {
      addFooter();
      doc.addPage();
      doc.setFillColor(...colors.bg);
      doc.rect(0, 0, pageWidth, pageHeight, "F");
      y = 48;
    }
  }

  function addTopLabel(text: string, white = false) {
    const labelColor: [number, number, number] = white
      ? [255, 255, 255]
      : colors.muted;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...labelColor);
    doc.text(text.toUpperCase(), marginX, y);
    y += 18;
  }

  function addBigTitle(
    text: string,
    fontSize = 28,
    white = false,
    lineGap = 30
  ) {
    const titleColor: [number, number, number] = white
      ? [255, 255, 255]
      : colors.text;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(fontSize);
    doc.setTextColor(...titleColor);

    const lines = doc.splitTextToSize(text, contentWidth);
    lines.forEach((line: string) => {
      doc.text(line, marginX, y);
      y += lineGap;
    });
    y += 6;
  }

  function addSubtitle(text: string, white = false) {
    const subtitleColor: [number, number, number] = white
      ? [220, 225, 235]
      : colors.muted;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...subtitleColor);

    const lines = doc.splitTextToSize(text, contentWidth);
    lines.forEach((line: string) => {
      doc.text(line, marginX, y);
      y += 20;
    });
    y += 6;
  }

  function addDivider(light = false) {
    const dividerColor: [number, number, number] = light
      ? [255, 255, 255]
      : colors.line;

    doc.setDrawColor(...dividerColor);
    doc.line(marginX, y, pageWidth - marginX, y);
    y += 18;
  }

  function addSectionHeader(
    title: string,
    color: [number, number, number] = colors.orange
  ) {
    ensureSpace(40);

    doc.setFillColor(...color);
    doc.roundedRect(marginX, y - 11, 10, 10, 3, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(...colors.text);
    doc.text(title, marginX + 20, y);
    y += 18;

    doc.setDrawColor(...colors.line);
    doc.line(marginX, y, pageWidth - marginX, y);
    y += 18;
  }

  function addParagraph(
    text: string,
    fontSize = 11,
    muted = false,
    lineHeight = 17
  ) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(...(muted ? colors.muted : colors.text));
    const lines = doc.splitTextToSize(text, contentWidth);
    ensureSpace(lines.length * lineHeight + 8);

    lines.forEach((line: string) => {
      doc.text(line, marginX, y);
      y += lineHeight;
    });
    y += 8;
  }

  function addBullets(items: string[]) {
    items.forEach((item) => {
      const bulletWidth = contentWidth - 18;
      const lines = doc.splitTextToSize(item, bulletWidth);
      ensureSpace(lines.length * 17 + 10);

      doc.setFillColor(...colors.orange);
      doc.circle(marginX + 4, y - 4, 3, "F");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(...colors.text);

      lines.forEach((line: string, index: number) => {
        doc.text(line, marginX + 16, y + index * 17);
      });

      y += lines.length * 17 + 8;
    });
    y += 4;
  }

  function addCard(
    title: string,
    bodyLines: string[],
    accent: [number, number, number]
  ) {
    const bodyHeight = bodyLines.reduce((sum, line) => {
      const wrapped = doc.splitTextToSize(line, contentWidth - 40);
      return sum + wrapped.length * 16;
    }, 0);

    const cardHeight = 24 + 22 + bodyHeight + 18;
    ensureSpace(cardHeight);

    doc.setFillColor(...colors.card);
    doc.setDrawColor(...colors.line);
    doc.roundedRect(marginX, y, contentWidth, cardHeight, 12, 12, "FD");

    doc.setFillColor(...accent);
    doc.roundedRect(marginX, y, 8, cardHeight, 8, 8, "F");

    let innerY = y + 24;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...colors.text);
    doc.text(title, marginX + 20, innerY);

    innerY += 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...colors.text);

    bodyLines.forEach((line) => {
      const wrapped = doc.splitTextToSize(line, contentWidth - 40);
      wrapped.forEach((w: string) => {
        doc.text(w, marginX + 20, innerY);
        innerY += 16;
      });
      innerY += 2;
    });

    y += cardHeight + 14;
  }

  function addScoreBars() {
    addSectionHeader("Category Breakdown", colors.blue);

    categoryCards.forEach((item) => {
      ensureSpace(38);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...colors.text);
      doc.text(item.label, marginX, y);

      doc.text(`${item.value}/100`, pageWidth - marginX, y, {
        align: "right",
      });
      y += 12;

      doc.setFillColor(...colors.line);
      doc.roundedRect(marginX, y, contentWidth, 10, 5, 5, "F");

      doc.setFillColor(...colors.orange);
      doc.roundedRect(
        marginX,
        y,
        Math.max(16, (contentWidth * item.value) / 100),
        10,
        5,
        5,
        "F"
      );

      y += 24;
    });

    y += 4;
  }

  function addShopBlocks() {
    addSectionHeader("Best Places To Shop", colors.teal);

    (aiReport.bestPlacesToShop || []).forEach((item, index) => {
      const accentPool: [number, number, number][] = [
        colors.teal,
        colors.orange,
        colors.blue,
        colors.pink,
      ];

      addCard(
        item.challenge,
        [
          `Shop for: ${item.whatToShop}`,
          `Where to buy: ${(item.whereToBuy || []).join(", ")}`,
          item.reason,
        ],
        accentPool[index % accentPool.length]
      );
    });
  }

  function addPlanBlocks() {
    addSectionHeader("Your 30-Day Style Upgrade Plan", colors.purple);

    (aiReport.plan30Days || []).forEach((block, index) => {
      const accentPool: [number, number, number][] = [
        colors.orange,
        colors.blue,
        colors.green,
        colors.amber,
        colors.teal,
        colors.pink,
        colors.purple,
      ];

      const bodyLines = [
        `Focus: ${block.focus}`,
        ...block.actions.map((a) => `• ${a}`),
      ];

      addCard(
        block.days,
        bodyLines,
        accentPool[index % accentPool.length]
      );
    });
  }

  function addCoverPage() {
    doc.setFillColor(...colors.darkCover);
    doc.rect(0, 0, pageWidth, pageHeight, "F");

    doc.setFillColor(...colors.darkCover2);
    doc.circle(pageWidth - 70, 110, 110, "F");
    doc.circle(90, pageHeight - 120, 120, "F");

    y = 68;


    addBigTitle(
      aiReport.title || "Your 30-Day Style Upgrade Blueprint",
      28,
      true,
      30
    );
    addSubtitle(
      aiReport.subtitle ||
        "A premium style blueprint built from your quiz answers, body type, work environment, budget, and lifestyle.",
      true
    );

    y += 18;

    doc.setFillColor(255, 255, 255);
    doc.setTextColor(...colors.darkCover);
    doc.roundedRect(marginX, y, contentWidth, 104, 18, 18, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Overall Style Score", marginX + 24, y + 28);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(36);
    doc.text(`${result.overall_score}/100`, marginX + 24, y + 72);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Archetype: ${archetype.title}`, marginX + 230, y + 40);
    doc.text(
      `Confidence: ${String(result.confidence_level).toUpperCase()}`,
      marginX + 230,
      y + 64
    );

    y += 138;

    addDivider(true);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(220, 225, 235);

    const coverText = doc.splitTextToSize(
      "This report is tailored to your current style score, strengths, weak areas, lifestyle context, and upgrade priorities. Use it as a practical 30-day blueprint to improve how you present yourself.",
      contentWidth
    );

    coverText.forEach((line: string) => {
      doc.text(line, marginX, y);
      y += 18;
    });

    addFooter();
    doc.addPage();
    doc.setFillColor(...colors.bg);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    y = 48;
  }

  doc.setFillColor(...colors.bg);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  addCoverPage();


  addBigTitle(aiReport.title || "Your Personal Style Upgrade Report");
  addSubtitle(
    "Tailored strategies for your current style score, goals, lifestyle, and biggest opportunities."
  );
  addDivider();

  addCard(
    "Score Summary",
    [
      `Overall Style Score: ${result.overall_score}/100`,
      `Style Archetype: ${archetype.title}`,
      `Confidence Level: ${result.confidence_level}`,
    ],
    colors.orange
  );

  addSectionHeader("Style Snapshot", colors.blue);
  addParagraph(aiReport.snapshot || "");

  addSectionHeader("What You Already Do Well", colors.green);
  addBullets(aiReport.strengths || []);

  addSectionHeader("What Is Holding You Back", colors.amber);
  addBullets(aiReport.opportunities || []);

  addSectionHeader("Your Top 3 Priorities", colors.pink);
  addBullets(aiReport.topPriorities || []);

  addScoreBars();

  addSectionHeader("What To Buy Next", colors.orange);
  addBullets(aiReport.buyNext || []);

  addShopBlocks();
  addPlanBlocks();

  addSectionHeader("Final Confidence Advice", colors.pink);
  addParagraph(aiReport.confidenceAdvice || "");

  addFooter();
  doc.save("stylescore-premium-style-blueprint.pdf");
}
